import { withIronSessionSsr } from "iron-session/next";
import { NextPage } from "next";
import Head from 'next/head'
import { useEffect } from "react";
import FormFrameContainer from "../../../components/admin/FormFrame/FormFrameContainer";
import { useAppDispatch } from "../../../hooks";
import { SagaActions } from "../../../store/sagas";

const EventsPage: NextPage = (props: any) =>{
    const dispatch = useAppDispatch();

    useEffect(() => {
        dispatch({ type: SagaActions.SET_FORM_DEFINITIONS, FID: "Event" });
    }, [dispatch])

    return (
        <div className={""}>
            <Head>
                <title>Stránky</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={""}>
                <FormFrameContainer />
            </main>
        </div>
    )

}

export const getServerSideProps = withIronSessionSsr(
    async ({ req, res }) => {
        const adminLogged: boolean | undefined = req.session.adminLogged;

        if (adminLogged
        ) {
            return {
                props: {},
            };
        } else {
            return {
                redirect: {
                    destination: '/admin/login',
                    permanent: false,
                }
            };
        }
    },
    {
        cookieName: "myapp_cookiename",
        cookieOptions: {
            secure: process.env.NODE_ENV === "production" ? true : false,
        },
        password: "P5hBP4iHlvp6obqtWK0mNuMrZow5x6DQV61W3EUG",
    }
);

export default EventsPage;