import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { getApiURL } from '../../utils'
import classes from './adminStyles.module.scss'

const AdminDocumentsPage: NextPage = (props: any) => {
  const documents: Array<any> = (props.docs) ? props.docs : [];


  return (
    <div className={classes.container}>
      <Head>
        <title>Stránky</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={classes.main}>
        <h1 className="text-center mb-4">Dokumenty</h1>
        <table className={classes.table}>
          <tr className={classes.tr}>
            <th className={classes.th}>Otevřít dokument</th>
            <th className={classes.th}>Název dokumentu</th>
            <th className={classes.th}>URL</th>
            <th className={classes.th}>Akce</th>
          </tr>
          {documents.map((doc, index) => {
            console.log('doc: ', doc);
            const url = (doc?.url?.startsWith("/")) ? doc.url.substring(1) : doc.url;
            return (
              <tr key={"doc-" + index} className={classes.tr}>
                <td className={classes.td}><Link href={"/dokumenty/" + url}><a target="_blank" className="fw-bold h5">Otevřít dokument</a></Link></td>
                <td className={classes.td}>{doc.name}</td>
                <td className={classes.td}>{"/dokumenty/" + url}</td>
              </tr>
            )
          })}
          <tr>
            <th colSpan={3}><span>Přidat nový dokument</span></th>
          </tr>
        </table>
      </main>
    </div>
  )
}

export default AdminDocumentsPage

export const getServerSideProps = async (req, res) => {
  let docs = await (await fetch(getApiURL("getDocuments"))).json();

  return {
    props: { docs },
  };
}