import type { NextPage } from 'next'
import Head from 'next/head'
import styles from './pages.module.scss'

const AdminContactsPage: NextPage = (props: any)  => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Stránky</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        kontakt
      </main>
    </div>
  )
}

export default AdminContactsPage
