import type { NextPage } from 'next'
import Head from 'next/head'
import AppTable from '../../components/Table/Table'
import styles from './pages.module.scss'

const Pages: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Stránky</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <AppTable />
      </main>
    </div>
  )
}

export default Pages
