
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { FC, MouseEventHandler, useState } from 'react';
import AppTable from '../../shared/components/Table/Table';
import { getApiURL } from '../../FilesToDistribute/utils';
import classes from "./dokumenty.module.scss";
import { cookies } from 'next/headers';
import { getIronSession } from 'iron-session';
import { sessionOptions } from '../../features/auth/sessionConfig';


const AdminDocumentsPage: NextPage = (props: any) => {
    const documents: Array<any> = (props.docs) ? props.docs : [];
    const [fileManagerVisible, setFileManagerVisible] = useState(false);
    const [modalVisible, setModalVisible] = useState(false);
    const [deletedDocumentName, setDeletedDocumentName] = useState("")
    const [deletedDocumentID, setDeletedDocumentID] = useState(-1)

    const showFileManager = () => {
        setFileManagerVisible(true);
    }

    const hideFileManager = () => {
        setFileManagerVisible(false)
    }

    const deleteDocumentConfirmation = (name, id_document) => {
        setDeletedDocumentID(id_document);
        setDeletedDocumentName("\"" + name + "\"");
        setModalVisible(true);
    }

    const cancelDeletion = () => {
        setDeletedDocumentName("");
        setDeletedDocumentID(-1);
        setModalVisible(false);
    }

    const deleteDocument = async (event) => {
        // event.preventDefault();
        setDeletedDocumentName("");
        setDeletedDocumentID(-1);
        setModalVisible(false);
        const body = JSON.stringify({ id: deletedDocumentID });
        const result = await fetch("/api/admin/deleteDocument",
            {
                method: "POST",
                mode: "same-origin",
                headers: { "Content-Type": "application/json" },
                body
            })
        if (result.status == 200) {
            window.location.reload();
        }
    }

    const headerItems = [
        { content: "Název dokumentu" },
        { content: "URL" },
        { content: "Akce" },
    ]

    const bodyRows: Array<any> =
        documents.map((doc, index) => {
            const url = (doc?.url?.startsWith("/")) ? doc.url.substring(1) : doc.url;
            return {
                items: [
                    { content: doc.name, className: "word-break-all" },
                    { content: (<Link href={"/dokumenty/" + url} target="_blank" className={"link"}>{"/dokumenty/" + url}</Link>), className: "word-break-all" },
                    { className: "actions", content: (<><span className={"link-danger"} onClick={deleteDocumentConfirmation.bind(this, doc.name, doc.id_document)}>Smazat</span><span className={"link"}>Přejmenovat</span></>) }
                ]
            };

        })
    /*
        bodyRows.unshift({
            items: [{
                colspan: 4,
                content: (<>
                    {!fileManagerVisible && <span className={"link " + "add-document-btn mb-3"} onClick={showFileManager}>Přidat nový dokument</span>}
                    {fileManagerVisible && <NewDocumentManager hideFileManager={hideFileManager} />}
                </>),
                className: "text-center"
            }]
        })*/

    return (
        <div className={""}>
            <Head>
                <title>Admin - Dokumenty</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={""}>
                <h1 className="text-center mb-4">Dokumenty</h1>
                <div className={"form-wrapper"}>
                    {!fileManagerVisible && <span className={"link " + "add-document-btn mb-3"} onClick={showFileManager}>Přidat nový dokument</span>}
                    {fileManagerVisible && <NewDocumentManager hideFileManager={hideFileManager} />}
                    <AppTable headerItems={headerItems} bodyRows={bodyRows} />
                    {modalVisible && <Modal deletedDocumentName={deletedDocumentName} cancelDeletion={cancelDeletion} deleteDocument={deleteDocument} />}
                </div>
            </main>
        </div>
    )
}

type NewDocumentManagerProps = {
    hideFileManager: MouseEventHandler<HTMLInputElement>
}

const NewDocumentManager: FC<NewDocumentManagerProps> = ({
    hideFileManager
}) => {
    const [fileLabel, setFileLabel] = useState("Vyberte soubor")
    const [file, setFile] = useState(undefined);
    const initFileName = "Název souboru";
    const [fileName, setFileName] = useState(initFileName);
    const [urlName, setUrlName] = useState("");

    const fileChange = (event) => {
        if (event?.target?.files[0]?.name?.length) {
            const f = event.target.files[0];
            setFile(f);
            setUrlName(f.name);
            setFileLabel("Vybráno: " + f.name);
            if (fileName === initFileName || fileName === "") {
                setFileName(f.name);
            }
        }
    }

    const uploadToServer = async (event) => {
        event.preventDefault();
        if (file == undefined) {
            throw new Error("file is undefined!");
        }
        const body = new FormData();
        body.append("document", file);
        body.append("url", urlName);
        body.append("name", fileName);
        const response = await fetch("/api/admin/addDocument", {
            method: "POST",
            body
        });

        if (response.status == 200) {
            window.location.reload();
        }
    };

    const fileNameChanged = (e) => {
        setFileName(e.target.value);
    }

    const clearFileName = (e) => {
        if (fileName === initFileName) {
            setFileName("");
        }
    }
    return (
        <div className="bordered mb-3">
            <form className="d-flex flex-column" onSubmit={uploadToServer}>
                <input type="file" onChange={fileChange} name="file" id="file" className={"hidden-file-input"} />
                <div className="d-flex justify-content-center">
                    <label htmlFor="file" className="hidden-file-input-label">{fileLabel}</label>
                </div>
                <div className="d-flex justify-content-center">
                    <input type="text" onChange={fileNameChanged} onClick={clearFileName} name="file-name" id="file-name" className={classes.fileName} value={fileName} placeholder={initFileName} />
                </div>
                <div className="d-flex justify-content-center">
                    <input className="button" type="submit" value="Uložit" />
                    <input className="button button-danger" onClick={hideFileManager} type="button" value="Zrušit" />
                </div>
            </form>
        </div>
    )
}

type ModalProps = {
    cancelDeletion: MouseEventHandler<HTMLDivElement | HTMLButtonElement>,
    deleteDocument: MouseEventHandler<HTMLButtonElement>,
    deletedDocumentName: string
}

const Modal: FC<ModalProps> = ({
    cancelDeletion,
    deleteDocument,
    deletedDocumentName
}) => {


    return (
        <div className="modal-window">
            <div className="overlay" onClick={cancelDeletion}>

            </div>
            <div className="content">
                <div className="text">
                    Jste si jistí, že chcete dokument {deletedDocumentName} odstranit?
                </div>
                <div className="btns-container">
                    <button className="btn btn-lg btn-danger" onClick={deleteDocument}>Odstranit</button>
                    <button className="btn btn-lg btn-primary" onClick={cancelDeletion}>Ponechat</button>
                </div>

            </div>
        </div>
    )
}

export const getServerSideProps = async (context) => {
    const { req, res } = context;
    const session = await getIronSession(req, res, sessionOptions);
    const adminLogged: boolean | undefined = (session as any).adminLogged;

    if (adminLogged
    ) {

        let docs = await (await fetch(getApiURL("getDocuments"))).json();
        return {
            props: { docs },
        };
    } else {
        return {
            redirect: {
                destination: '/admin/login',
                permanent: false,
            }
        };
    }
}

export default AdminDocumentsPage;