import type { NextPage } from 'next'
import { withIronSessionApiRoute, withIronSessionSsr } from "iron-session/next";
import Head from 'next/head'
import FormFrameContainer from '../../components/admin/FormFrame/FormFrameContainer'
import styles from './pages.module.scss'
import { useDispatch } from 'react-redux';
import { useEffect } from 'react';
import { SagaActions } from '../../store/sagas';

const AdminFoodPage: NextPage = (props: any) => {
    const dispatch = useDispatch();

    useEffect(() => {
        dispatch({ type: SagaActions.SET_FORM_DEFINITIONS, FID: "Food" });
    }, [dispatch])

    return (
        <div className={styles.container}>
            <Head>
                <title>Stránky</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={""}>
                <FormFrameContainer />
            </main>
        </div>
    )
}

export const getServerSideProps = withIronSessionSsr(
    async ({ req, res }) => {
        const adminLogged: boolean = req.session.adminLogged;

        if (adminLogged
        ) {
            return {
                props: {},
            };
        } else {
            return {
                redirect: {
                    destination: '/admin/login',
                    permanent: false,
                }
            };
        }
    },
    {
        cookieName: "myapp_cookiename",
        cookieOptions: {
            secure: process.env.NODE_ENV === "production" ? true : false,
        },
        password: "P5hBP4iHlvp6obqtWK0mNuMrZow5x6DQV61W3EUG",
    }
);

export default AdminFoodPage
