import type { NextPage } from 'next'
import { withIronSessionApiRoute, withIronSessionSsr  } from "iron-session/next";;
import Head from 'next/head'
//import styles from '../styles/Home.module.css'
const styles:any = {};
const AdminHomePage: NextPage = (props: any)  => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        Uvod
      </main>
    </div>
  )
}

export const getServerSideProps = withIronSessionSsr(
  async ({ req, res }) => {
    const adminLogged: boolean | undefined = req.session.adminLogged;

    if (adminLogged
    ) {
      return {
        props: {},
      };
    } else {
      return {
        redirect: {
          destination: '/admin/login',
          permanent: false,
        }
      };
    }
  },
  {
    cookieName: "myapp_cookiename",
    cookieOptions: {
      secure: process.env.NODE_ENV === "production" ? true : false,
    },
    password: "P5hBP4iHlvp6obqtWK0mNuMrZow5x6DQV61W3EUG",
  }
);

export default AdminHomePage
