
import { getIronSession } from 'iron-session';
import type { NextPage } from 'next';
import Head from 'next/head';
import { cookies } from 'next/headers';
import { sessionOptions } from '../../helpers/sessionConfig';
;
//import styles from '../styles/Home.module.css'
const styles: any = {};
const AdminHomePage: NextPage = (props: any) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <p>Vlevo vyberte kategorii k editaci.</p>
            </main>
        </div>
    )
}

export const getServerSideProps = async (context) => {
    const { req, res } = context;
    const session = await getIronSession(req, res, sessionOptions);
    const adminLogged: boolean | undefined = (session as any).adminLogged;

    if (adminLogged
    ) {
        return {
            props: {},
        };
    } else {
        return {
            redirect: {
                destination: '/admin/login',
                permanent: false,
            }
        };
    }
}

export default AdminHomePage;
