import { FC, useEffect, useState } from "react";
import useAppDispatch from "../../../hooks/useAppDispatch";
import { SagaActions } from "../../../store/sagas";
import useSelector from "../../../hooks/useAppSelector";
import { RootState } from "../../../helpers/types";
import Head from "next/head";
import FormFrameContainer from "../FormFrame/FormFrameContainer";
import { selectActualDBOClass } from "../../../store/formDefReducer/selector";

type AdminPageProps = {
    formID: string
}

const AdminPage: FC<any> = ({
    formID
}) =>{
    // eslint-disable-next-line react/display-name
        const dispatch = useAppDispatch();
        const [pageFormDefinitionLoaded, setPageFormDefinitionLoaded] = useState(false);
        const DBOClass = useSelector((state: RootState) => selectActualDBOClass(state));

        useEffect(() => {
            dispatch({ type: SagaActions.SET_FORM_DEFINITIONS, FID: formID });
        // eslint-disable-next-line react-hooks/exhaustive-deps
        }, [dispatch])

        useEffect(() => {
            setPageFormDefinitionLoaded(true)
        }, [DBOClass])

        //return <Page {...props} pageFormDefLoaded={pageFormLoaded} />;

        return (

            <div className={""}>
                <Head>
                    <title>Web</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={""}>
                    {pageFormDefinitionLoaded && <FormFrameContainer />}
                </main>
            </div>
        )
}


export default AdminPage;